# Generated by Django 3.2 on 2024-10-07 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyapp', '0002_study_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='study',
            unique_together={('user', 'study_name', 'study_phase')},
        ),
    ]
