# Generated by Django 3.2 on 2024-10-07 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studyapp', '0003_alter_study_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='study',
            unique_together={('user', 'study_name')},
        ),
    ]
