# Generated by Django 3.2 on 2024-10-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0004_auto_20241008_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_phase',
            field=models.CharField(choices=[('Phase I', 'Phase I'), ('Phase II', 'Phase II'), ('Phase III', 'Phase III'), ('Phase IV', 'Phase IV')], max_length=10),
        ),
    ]
