# Generated by Django 3.2 on 2024-10-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_alter_study_study_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_description',
            field=models.TextField(),
        ),
    ]
